[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "discord-trades-mvp"
version = "0.1.0"
description = "MVP Discord reader that prints text output"
requires-python = ">=3.11"
dependencies = []

[tool.pyright]
typeCheckingMode = "basic"
